### ISSUE TITLE
.bib files getting deleted

### ISSUE THREAD

**Issue by vmurahari3** [google-research/arxiv-latex-cleaner#14]
Would be nice to add  .bib to the set of restricted file types which aren't deleted.

**Comment by jponttuset** [comment]
Hi @vmurahari3,
This is working as intended, as .bib files are expected to be deleted to submit to arXiv, only the .bbl file should be there.
Best,

**Comment by AndreiBarsan** [comment]
Related comment: I used to have `latexmk -c -bibtex` in my `make clean` command, which got run in a script before running the sanitizer to generate the arXiv output. This removed the `.bbl` file, and then the sanitizer wiped the `bib` files!

To avoid this issue, make sure you're not pre-deleting your `bbl` before running the sanitizer, since if you do, then your arXiv submission will be missing citations!

**Comment by jponttuset** [comment]
Hi folks, 
FYI, since v0.1.14, there is an option to keep the bib files: `--keep_bib`.
Best,
